Statement = "{", { Statement }, "}"
          | Type, Identifier, ";"
          | "while", "(", Expression, ")", "{", { Statement }, "}"
          | Lval, "=", Expression, ";"
          | Lval, "[", Expression, "]", "=", Expression, ";"
          | "if", "(", Expression, ")", Statement;


Lval = Identifier, { ".", Identifier };


Type = "int"
     | "int", "[", "]" 
     | "bool"
     | Identifier;


Identifier = ? IDENTIFIER ?;